version: '3'
services:
  mongo:
    container_name: mongo
    image: "metadatacenter/cedar-mongo"
    build: ../../cedar-docker-build/cedar-mongo
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MONGO_PORT}:27017"
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/mongo/:/data/db
      - ${CEDAR_DOCKER_HOME}/log/mongo/:/data/log
    environment:
      - CEDAR_MONGO_ROOT_USER_NAME
      - CEDAR_MONGO_ROOT_USER_PASSWORD
      - CEDAR_MONGO_APP_USER_NAME
      - CEDAR_MONGO_APP_USER_PASSWORD
      - CEDAR_HOST
      - CEDAR_ADMIN_USER_API_KEY

  redis-persistent:
    container_name: redis-persistent
    image: "metadatacenter/cedar-redis-persistent"
    build: ../../cedar-docker-build/cedar-redis-persistent
    networks:
      - cedarnet
    ports:
      - ${CEDAR_REDIS_PERSISTENT_PORT}:6379
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/redis/:/data
      - ${CEDAR_DOCKER_HOME}/log/redis/:/log
    sysctls:
      - net.core.somaxconn=512

  mysql:
    container_name: mysql
    image: "metadatacenter/cedar-mysql"
    build: ../../cedar-docker-build/cedar-mysql
    networks:
      - cedarnet
    ports:
      - ${CEDAR_MYSQL_PORT}:3306
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/mysql/:/var/lib/mysql
    environment:
      - CEDAR_MYSQL_ROOT_PASSWORD
      - CEDAR_MYSQL_USER
      - CEDAR_MYSQL_PASSWORD

  keycloak:
    container_name: keycloak
    image: "metadatacenter/cedar-keycloak"
    build: ../../cedar-docker-build/cedar-keycloak
    depends_on:
      - mysql
    networks:
      - cedarnet
    ports:
      - ${CEDAR_KEYCLOAK_PORT}:8080
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/keycloak:/opt/jboss/keycloak/standalone/log
    environment:
      - CEDAR_MYSQL_USER
      - CEDAR_MYSQL_PASSWORD
      - CEDAR_MYSQL_PORT
      - CEDAR_MYSQL_HOST
      - CEDAR_KEYCLOAK_ADMIN_USER
      - CEDAR_KEYCLOAK_ADMIN_PASSWORD
      - CEDAR_ADMIN_USER_API_KEY
      - CEDAR_HOST
      - CEDAR_NET_GATEWAY
      - CEDAR_RESOURCE_HTTP_PORT

  elasticsearch:
    container_name: elasticsearch
    image: "metadatacenter/cedar-elasticsearch"
    build: ../../cedar-docker-build/cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/elasticsearch:/usr/share/elasticsearch/data
      - ${CEDAR_DOCKER_HOME}/log/elasticsearch:/usr/share/elasticsearch/logs

  neo4j:
    container_name: neo4j
    image: "metadatacenter/cedar-neo4j"
    build: ../../cedar-docker-build/cedar-neo4j
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687
    volumes:
      - ${CEDAR_DOCKER_HOME}/data/neo4j/:/data
      - ${CEDAR_DOCKER_HOME}/log/neo4j/:/logs
    environment:
      - CEDAR_NEO4J_USER_PASSWORD

  nginx:
    container_name: nginx
    image: "metadatacenter/cedar-nginx"
    build: ../../cedar-docker-build/cedar-nginx
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NGINX_HTTP_PORT}:80
      - ${CEDAR_NGINX_HTTPS_PORT}:443
    volumes:
      - ${CEDAR_DOCKER_HOME}/log/:/etc/nginx/log
      - ${CEDAR_DOCKER_HOME}/cert/:/usr/local/etc/certificates
    environment:
      - CEDAR_HOST
      - CEDAR_MICROSERVICE_HOST
      - CEDAR_KEYCLOAK_HOST
      - CEDAR_FRONTEND_HOST


networks:
  cedarnet:
    external:
      name: cedarnet